### ISSUE TITLE
`cascade_and_unite` deserves an easier name to type

### ISSUE THREAD

**Issue by ajkeller34** [rigetti/AdmittanceModels.jl#10]
The name is good in that the functionality is self-evident if you have read the paper, but for such a common operation it is a drag to type that many characters.

I suggest `connect` to indicate that the operation amounts to connecting multiple admittance models (or circuits) at their shared ports.

**Comment by ajkeller34** [comment]
Some other possibilities include: `link`, `consolidate`, `merge`, `unify`, `intersect`

**Comment by onurbakir** [comment]
I vote for `connect`.  

Back in the day when writing an a SPICE file, you could define sub-circuits `.SUBCKT` and then you would `connect` them to the main circuit at nodes.
