### ISSUE TITLE
Register in General

### ISSUE THREAD

**Issue by amellnik** [rigetti/AdmittanceModels.jl#15]
I think the bot is now added so we can do this: @JuliaRegistrator register()

**Comment by amellnik** [comment]
It looks like we should add upper bounds to a few deps as per https://github.com/JuliaRegistries/General/pull/4510#issuecomment-543810679

**Comment by ajkeller34** [comment]
@JuliaRegistrator register()

**Comment by amellnik** [comment]
@JuliaRegistrator register()

**Comment by ajkeller34** [comment]
@JuliaRegistrator register()

**Comment by ajkeller34** [comment]
@JuliaRegistrator register()

**Comment by amellnik** [comment]
@JuliaRegistrator register()

**Comment by ajkeller34** [comment]
Looks like the PR was merged, so I will close this.
